apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  labels:
    name: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model
        image: ckn/model
        imagePullPolicy: Never
      restartPolicy: Always